apiVersion: apps/v1
kind: Deployment
metadata: 
  name: auth
  labels:
    app: auth
  namespace: fcc-microservices-auth

spec:
  replicas: 2
  selector:
    matchLabels: 
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: lucchini/fcc-microservices-auth
          # imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
