apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  MYSQL_HOST: mysql
  MYSQL_USER: fcc
  MYSQL_DB: fcc_micros
  MYSQL_PORT: "3306"
  MYSQL_PASSWORD: Admin_fcc123
  USERS_TABLE: users  