apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
spec:
  restartPolicy: Never
  containers:
  - name: mysql-client
    image: arm64v8/mysql:oracle
    args:
      - mysql
      - -h
      - mysql
      - -ppassword
    stdin: true
    tty: true